FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ENV DBT_HOME = /opt/dbt-project/

RUN mkdir -p $DAGSTER_HOME
RUN mkdir -p $DBT_HOME

COPY /dagster_project/dagster_prod.yaml $DAGSTER_HOME/dagster.yaml
COPY /dagster_project/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME